FROM python:3.12-slim
# Set proxy environment variables
ENV http_proxy=http://PROXY_USER:PROXY_PWD@radius.bs.ch:3128
ENV https_proxy=http://PROXY_USER:PROXY_PWD@radius.bs.ch:3128
# set work directory
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    vim \
    libssl-dev \
    libcurl4-gnutls-dev \
    curl \
    gnupg2 \
    libodbc2 \
	ca-certificates

RUN update-ca-certificates

RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc

RUN curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18

RUN apt-get clean  && rm -rf /var/lib/apt/lists/*


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
RUN pip install streamlit python-dateutil icalendar pytz Pillow
