# Stage 1: Build the application
FROM node:22-alpine3.21 AS build

# Set proxy environment variables
ENV http_proxy=http://PROXY_USER:PROXY_PWD@proxy.bs.ch:3128
ENV https_proxy=http://PROXY_USER:PROXY_PWD@proxy.bs.ch:3128

ENV DATABASE_URL=data/coursebooker.db

RUN apk update && apk add git
ENV NUXT_AZURE_AD_TENANT_ID="?AZURE_AD_TENANT_ID?"
ENV NUXT_AZURE_AD_CLIENT_ID="?AZURE_AD_CLIENT_ID?"
ENV NUXT_AZURE_AD_CLIENT_SECRET="?AZURE_AD_CLIENT_SECRET?"
ENV NUXT_AUTH_SECRET="?AUTH_SECRET?"
ENV AUTH_ORIGIN="?AUTH_ORIGIN?"

ENV SMTP_HOST=?SMTP_HOST?
ENV SMTP_PORT=?SMTP_PORT?

RUN apk update && apk add git

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./package*.json ./
COPY .npmrc ./
# COPY ./bun.lock ./

# Install dependencies using bun
RUN npm ci
RUN npm add @libsql/linux-x64-musl

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

COPY ./docker/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Expose the port the app runs on
EXPOSE 3000

# Start the application
ENTRYPOINT ["/app/entrypoint.sh"]