version: "3"
services:
  coursebooker:
    restart: always
    build: .
    command: python -m streamlit run app.py --logger.level=debug
    volumes:
      - ./app:/usr/src/app
      - ./data:/data
    ports:
      - 8502:8501
