<script setup lang="ts">
import type { CourseSession } from '~/../shared/models/session.model';
import type { Lesson } from '~/../shared/models/lession.model';

interface Props {
    session: CourseSession & { tempId: string };
    sessionNumber: number;
}

const props = defineProps<Props>();

const emit = defineEmits<{
    update: [session: CourseSession & { tempId: string }];
    delete: [];
}>();

function updateField(field: keyof CourseSession, value: string) {
    const updatedSession = { ...props.session };
    (updatedSession as any)[field] = value;
    emit('update', updatedSession);
}

function addLesson() {
    const newLesson: Lesson & { tempId: string } = {
        id: '', // Will be generated by the server
        tempId: Date.now().toString(), // Temporary ID for Vue key
        start: new Date(),
        end: new Date(Date.now() + 60 * 60 * 1000) // 1 hour later
    };

    const updatedSession = {
        ...props.session,
        lessons: [...props.session.lessons, newLesson]
    };

    emit('update', updatedSession);
}

function updateLesson(index: number, updatedLesson: Lesson & { tempId: string }) {
    const updatedSession = {
        ...props.session,
        lessons: props.session.lessons.map((lesson, i) =>
            i === index ? updatedLesson : lesson
        )
    };

    emit('update', updatedSession);
}

function removeLesson(index: number) {
    const updatedSession = {
        ...props.session,
        lessons: props.session.lessons.filter((_, i) => i !== index)
    };

    emit('update', updatedSession);
}
</script>


<template>
    <div class="border border-gray-200 rounded-lg p-4">
        <div class="flex items-center justify-between mb-4">
            <h4 class="text-lg font-medium text-gray-900">
                Session {{ sessionNumber }}
            </h4>
            <UButton color="red" variant="ghost" icon="i-heroicons-trash" size="sm" @click="$emit('delete')">
                Remove Session
            </UButton>
        </div>

        <div class="space-y-4">
            <!-- Location -->
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">
                    Location
                </label>
                <UInput :model-value="session.location" @update:model-value="updateField('location', $event)"
                    placeholder="Enter session location" />
            </div>

            <!-- Teams Link -->
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">
                    Teams Link (Optional)
                </label>
                <UInput :model-value="session.teams_link" @update:model-value="updateField('teams_link', $event)"
                    placeholder="https://teams.microsoft.com/..." />
            </div>

            <!-- Lessons -->
            <div>
                <div class="flex items-center justify-between mb-3">
                    <label class="block text-sm font-medium text-gray-700">
                        Lessons
                    </label>
                    <UButton type="button" color="primary" variant="outline" icon="i-heroicons-plus" size="sm"
                        @click="addLesson">
                        Add Lesson
                    </UButton>
                </div>

                <div v-if="session.lessons.length === 0" class="text-center py-4 text-gray-500 text-sm">
                    No lessons added yet.
                </div>

                <div v-else class="space-y-3">
                    <AdminLessonForm v-for="(lesson, index) in session.lessons" :key="lesson.tempId || lesson.id"
                        :lesson="lesson" :lesson-number="index + 1" @update="updateLesson(index, $event)"
                        @delete="removeLesson(index)" />
                </div>
            </div>
        </div>
    </div>
</template>
