<script setup lang="ts">
import type { Course, CourseType, Session } from '~~/shared/models';
import AdminHeader from '~/components/admin/AdminHeader.vue';
import AdminSessionForm from '~/components/admin/AdminSessionForm.vue';

// Page meta
definePageMeta({
    layout: false,
    title: 'Create Course'
});

// Form state
const submitting = ref(false);

// Course type options
const typeOptions = [
    { label: 'Course', value: 'course' },
    { label: 'Event', value: 'event' }
];

// Form data
const form = reactive({
    type: 'course' as CourseType,
    title: '',
    description: '',
    organizer_name: '',
    organizer_mail: '',
    teams_link: '',
    sessions: [] as (Session & { tempId: string })[]
});

// Computed
const isFormValid = computed(() => {
    return form.title.trim() !== '' &&
        form.description.trim() !== '' &&
        form.organizer_name.trim() !== '' &&
        form.organizer_mail.trim() !== '';
});

// Methods
function addSession() {
    const newSession: CourseSession & { tempId: string } = {
        id: '', // Will be generated by the server
        tempId: Date.now().toString(), // Temporary ID for Vue key
        location: '',
        teams_link: '',
        lessons: []
    };
    form.sessions.push(newSession);
}

function updateSession(index: number, updatedSession: CourseSession & { tempId: string }) {
    form.sessions[index] = updatedSession;
}

function removeSession(index: number) {
    form.sessions.splice(index, 1);
}

async function submitForm() {
    if (!isFormValid.value) return;

    submitting.value = true;

    try {
        // Prepare the course data
        const courseData: Omit<Course, 'id'> = {
            type: form.type,
            title: form.title.trim(),
            description: form.description.trim(),
            organizer_name: form.organizer_name.trim(),
            organizer_mail: form.organizer_mail.trim(),
            teams_link: form.teams_link.trim() || undefined,
            sessions: form.sessions.map(session => ({
                id: session.id,
                location: session.location,
                teams_link: session.teams_link,
                lessons: session.lessons
            }))
        };

        // Submit to API
        const newCourse = await $fetch<Course>('/api/courses', {
            method: 'POST',
            body: courseData
        });

        // Redirect to course list with success message
        await navigateTo('/admin/courses');

        // You might want to show a success toast here

    } catch (error) {
        console.error('Error creating course:', error);
        // Show error toast
    } finally {
        submitting.value = false;
    }
}

useHead({
    title: 'Create Course - Admin'
});
</script>


<template>
    <div class="min-h-screen bg-gray-50">
        <AdminHeader title="Create Course" />

        <div class="max-w-4xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
            <div class="bg-white shadow rounded-lg">
                <div class="px-6 py-4 border-b border-gray-200">
                    <h2 class="text-xl font-semibold text-gray-900">Course Information</h2>
                    <p class="text-sm text-gray-600 mt-1">Fill in the basic details for your new course.</p>
                </div>

                <form @submit.prevent="submitForm" class="p-6 space-y-6">
                    <!-- Course Type -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Course Type
                        </label>
                        <USelectMenu v-model="form.type" :options="typeOptions" placeholder="Select course type"
                            size="lg" required />
                    </div>

                    <!-- Course Title -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Course Title *
                        </label>
                        <UInput v-model="form.title" placeholder="Enter course title" size="lg" required />
                    </div>

                    <!-- Course Description -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Description *
                        </label>
                        <UTextarea v-model="form.description" placeholder="Describe what this course covers..." rows="4"
                            resize required />
                    </div>

                    <!-- Organizer Information -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-2">
                                Organizer Name *
                            </label>
                            <UInput v-model="form.organizer_name" placeholder="Enter organizer name" size="lg"
                                required />
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-2">
                                Organizer Email *
                            </label>
                            <UInput v-model="form.organizer_mail" type="email" placeholder="organizer@example.com"
                                size="lg" required />
                        </div>
                    </div>

                    <!-- Teams Link -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">
                            Microsoft Teams Link (Optional)
                        </label>
                        <UInput v-model="form.teams_link" placeholder="https://teams.microsoft.com/..." size="lg" />
                    </div>

                    <!-- Sessions Section -->
                    <div class="border-t border-gray-200 pt-6">
                        <div class="flex items-center justify-between mb-4">
                            <div>
                                <h3 class="text-lg font-medium text-gray-900">Sessions</h3>
                                <p class="text-sm text-gray-600">Add sessions to your course. Each session can contain
                                    multiple lessons.</p>
                            </div>
                            <UButton type="button" color="primary" variant="outline" icon="i-heroicons-plus"
                                @click="addSession">
                                Add Session
                            </UButton>
                        </div>

                        <div v-if="form.sessions.length === 0" class="text-center py-8 text-gray-500">
                            <UIcon name="i-heroicons-calendar-days" class="h-12 w-12 mx-auto mb-2 text-gray-300" />
                            <p>No sessions added yet. Click "Add Session" to get started.</p>
                        </div>

                        <div v-else class="space-y-4">
                            <AdminSessionForm v-for="(session, index) in form.sessions" :key="session.tempId"
                                :session="session" :session-number="index + 1" @update="updateSession(index, $event)"
                                @delete="removeSession(index)" />
                        </div>
                    </div>

                    <!-- Form Actions -->
                    <div class="flex justify-end space-x-4 pt-6 border-t border-gray-200">
                        <UButton type="button" color="gray" @click="$router.back()">
                            Cancel
                        </UButton>
                        <UButton type="submit" color="primary" :loading="submitting" :disabled="!isFormValid">
                            Create Course
                        </UButton>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>